repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
        types: [file]
        files: '^.*.(dsl)$'
    -   id: end-of-file-fixer
        types: [file]
        files: '^.*.(dsl)$'
